Add Topic: Probability
PatrickMassot/GlimpseOfLean pull request #13
Opened 2024-09-23 09:55 UTC by LorenzoLuccioli

Add the file Topics.Probability with some simple exercises about probability theory, independence of sets, definition of conditional probability and Bayes' theorem.

- [x] depends on: #12

2024-09-23 11:38 UTC, RemyDegenne commented
You should also add the file to the list of topics files at the bottom of `03Forall.lean` (in both exercises and solutions).

2024-09-23 20:18 UTC, pitmonticone requested changes
There are a few minor typos. You can directly commit the suggested changes.

2024-09-23 20:18 UTC, pitmonticone commented on GlimpseOfLean/Exercises/Topics/Probability.lean
> +Measures can in general take infinite values, but since our `ℙ` is a probabilty measure,
```suggestion
Measures can in general take infinite values, but since our `ℙ` is a probability measure,
```

2024-09-23 20:18 UTC, pitmonticone commented on GlimpseOfLean/Solutions/Topics/Probability.lean
> +Measures can in general take infinite values, but since our `ℙ` is a probabilty measure,
```suggestion
Measures can in general take infinite values, but since our `ℙ` is a probability measure,
```

2024-09-23 20:18 UTC, pitmonticone commented on GlimpseOfLean/Exercises/Topics/Probability.lean
> +/-- Two sets `A, B` are independent for the ambiant probability measure `ℙ` if
```suggestion
/-- Two sets `A, B` are independent for the ambient probability measure `ℙ` if
```

2024-09-23 20:18 UTC, pitmonticone commented on GlimpseOfLean/Solutions/Topics/Probability.lean
> +/-- Two sets `A, B` are independent for the ambiant probability measure `ℙ` if
```suggestion
/-- Two sets `A, B` are independent for the ambient probability measure `ℙ` if
```

2024-09-23 22:19 UTC, pitmonticone approved these changes
Now it looks good to me.

2024-09-24 08:48 UTC, fpvandoorn commented
For future reference: the script `mk_exercises.py` generates the exercise files from the solution files (if the solution file is properly marked with `-- sorry` comments)

2024-09-24 08:49 UTC, fpvandoorn commented
The new probability file should probably get `-- sorry` commands so that the script also works for it.

2024-09-24 16:07 UTC, PatrickMassot commented
Thanks! Indeed it needs to be adapted to work with `mk_exercises`.

2024-09-24 16:28 UTC, pitmonticone requested changes

2024-09-24 16:29 UTC, pitmonticone commented
@LorenzoLuccioli You just need to commit the suggested changes and run: 

```bash
python3 mk_exercises.py
```

2024-09-25 09:18 UTC, pitmonticone commented
Ok, now it looks good to me. 

Thank you again @LorenzoLuccioli!

2025-02-19 10:58 UTC, fpvandoorn reviewed
LGTM, but here are two comments.

2025-02-19 10:58 UTC, fpvandoorn commented on GlimpseOfLean/Solutions/Topics/Probability.lean
> +-- Did you really need all those hypotheses?
This needs more explanation. What is division by 0? You have to explain that

2025-02-19 10:58 UTC, fpvandoorn commented on GlimpseOfLean/Solutions/Topics/Probability.lean
> +    IndepSet A B → IndepSet A Bᶜ := by {
It might be good practice to add another exercise that turns this into an `iff` (apply this lemma twice and use `compl_compl`)

2025-02-19 11:00 UTC, PatrickMassot commented
I’m sorry this was somehow forgotten. Thanks Floris for the comments! @LorenzoLuccioli could you rebase this on the master branch? I promise we won’t let it rot a second time.

2025-03-07 13:29 UTC, fpvandoorn commented
Thanks!

2025-03-07 13:30 UTC, merged